CREATE TABLESPACE TBS_FACT_PART_T1
ADD DATAFILE 'TBS_FACT_PART_T1.ibd' Engine=InnoDB
AUTOEXTEND_SIZE = 12M;

CREATE TABLESPACE TBS_FACT_PART_T2
ADD DATAFILE 'TBS_FACT_PART_T2.ibd' Engine=InnoDB
AUTOEXTEND_SIZE = 12M;

CREATE TABLESPACE TBS_FACT_PART_T3
ADD DATAFILE 'TBS_FACT_PART_T3.ibd' Engine=InnoDB
AUTOEXTEND_SIZE = 12M;

CREATE TABLESPACE TBS_FACT_PART_T4
ADD DATAFILE 'TBS_FACT_PART_T4.ibd' Engine=InnoDB
AUTOEXTEND_SIZE = 12M;