CREATE TABLE TB_FATO
(
    ID_CANAL VARCHAR(20) NOT NULL,
    ID_PRODUTO VARCHAR(20) NOT NULL,
    ID_CLIENTE VARCHAR(20) NOT NULL,
    ID_DATA VARCHAR(20) NOT NULL,
    VALOR_VENDA DECIMAL(9,2) NOT NULL,

        CONSTRAINT TB_FATO_PK
            PRIMARY KEY (ID_CLIENTE, ID_PRODUTO, ID_CANAL, ID_DATA)
)
PARTITION BY RANGE COLUMNS (ID_DATA)(
    PARTITION TBS_FACT_PART_T1 VALUES LESS THAN ('20170331'),
    PARTITION TBS_FACT_PART_T2 VALUES LESS THAN ('20170630'),
    PARTITION TBS_FACT_PART_T3 VALUES LESS THAN ('20170930'),
    PARTITION TBS_FACT_PART_T4 VALUES LESS THAN ('20171231')
);